liste = ['bases','conditions','listes','dictionnaires','boucles','fonctions']


def liste_correction(num):
    correction = {
        'bases' : "**Correction Exercice : Bases**\n"
                 "*Pour cet exercice il vous fallait utiliser les fonctions **input()** avec **str,int,float**,**les calcules de variable** et pour teminer le **print()** voici une correction parmit tant d'autre : *\n\n"
                 "```Nom = str(input('Quelle est votre nom ?'))\n"
                 "Prenom = str(input('Quelle est votre prénom?'))\n"
                 "Age = int(input('Quelle est votre âge ?'))\n"
                 "Taille = float(input('Quelle est votre taille ? (en m)'))\n"
                 "Poids = float(input('Quelle est votre poids ? (en kg)'))\n"
                 "IMC = Poids / (Taille * Taille)\n" 
                 "print(f'Bonjour vous êtes {Nom} {Prenom}, vous avez {Age}ans et votre IMC est de {round(IMC,1)}')```"
                 "\n*Comme vous pouvez le remarquer la fonction **round()** a été utilisé, elle fonctionne simplement avec 2 arguments le premier argument est le nombre que vous souhaitez arrondir et le deuxième à combien de chiffre après la virgule.\n"
                 "On peux aussi remarquer que j'ai utilisé **''** pour le texte, personnelement je vous conseille plustôt d'utiliser "
                 '**""** pour ensuite pouvoir écrire des mots comme'
                 " l'arbre ou d'autres mots avec apostrophe.* \n\n"
                 "Si tu as réussi cet exercice **Bien joué** tu peux passer à l'apprentissage des **Conditions** parcontre si tu as pas réussi ou que tu es pas sur d'avoir compris hésites pas à recommencer l'apprentissage ou à m'envoyer un message privé pour que je t'explique !",

        'conditions' : "**Correction Exercice : Conditions**\n"
                       "*Pour cet exercice toutes les notions vu dans l'exercice précédent sont demandé avec les conditions **if, elif, else**. De plus il vous fallait utiliser **and** à chaque codition sauf la dernière **elif**. Voici donc la correction : *\n\n"
                       "```Nom = str(input('Quelle est votre nom ?'))\n"
                       "Prenom = str(input('Quelle est votre prénom?'))\n"
                       "Age = int(input('Quelle est votre âge ?'))\n"
                       "Taille = float(input('Quelle est votre taille ? (en m)'))\n"
                       "Poids = float(input('Quelle est votre poids ? (en kg)'))\n"
                       "IMC = Poids / (Taille * Taille)\n"
                       "if IMC <= 18.5:\n"
                       "    print(f'{Prenom} {Nom} vous avez {Age} et votre IMC est de {IMC}, vous êtes considéré comme étant en Maigreur !')\n"
                       "elif IMC >= 18.6 and IMC < 25:\n"
                       "    print(f'{Prenom} {Nom} vous avez {Age} et votre IMC est de {IMC}, vous êtes considéré comme étant en Corpulence normal!')\n"
                       " elif IMC >= 25 and IMC < 30:\n"
                       "     print(f'{Prenom} {Nom} vous avez {Age} et votre IMC est de {IMC}, vous êtes considéré comme étant en Surpoids!')\n"
                       " elif IMC >= 30 and IMC < 35:\n"
                       "     print(f'{Prenom} {Nom} vous avez {Age} et votre IMC est de {IMC}, vous êtes considéré comme étant en Obésité modérée!')\n"
                       " elif IMC >= 35 and IMC < 40:\n"
                       "     print(f'{Prenom} {Nom} vous avez {Age} et votre IMC est de {IMC}, vous êtes considéré comme étant en Obésité élevé!')\n"
                       " elif IMC >= 40:\n"
                       "     print(f'{Prenom} {Nom} vous avez {Age} et votre IMC est de {IMC}, vous êtes considéré comme étant en Obésite morbide ou massive !'```"
                       "\n*Pour réaliser cet exercice on aurai pu utiliser une autre méthode plus simple ou on utiliserai pas de **and**, vous pouvez la voir en marquant **!correction conditions2***"
                       "\n\n*Si tu as réussi cet exercice **Bien joué** tu peux passer à l'apprentissage des **Listes** parcontre si tu as pas réussi ou que tu es pas sur d'avoir compris hésites pas à recommencer l'apprentissage ou à m'envoyer un message privé pour que je t'explique !*",

        'listes':   "**Correction Exercice : Listes**\n"
                    "*Pour cet exercice vous aviez besoin d'utiliser un peu tout ce qu'on a vu ensemble depuis le début que ce soit les listes ou les conditions accompagné des bases. Voici donc la correction : *\n"
                    "```sex = int(input('Quel est votre sex ?(0 : Femme,1 : Homme)'))\n"
                    "Nom = str(input('Quelle est votre nom ?'))\n"
                    "Prenom = str(input('Quelle est votre prénom?'))\n"
                    "Age = int(input('Quelle est votre âge ?'))\n\n"
                    "Liste = ['Femme', 'Homme']\n"
                    "if sex == 0:\n"
                    "    sex = 1\n"
                    "else:\n"
                    "    sex = 0\n\n"
                    "Liste.remove(Liste[sex])\n"
                    "Liste.append(Nom)\n"
                    "Liste.append(Prenom)\n"
                    "Liste.append(Age)\n\n"
                    
                    "print(Liste, len(Liste))```"
                    "\n\n*Si tu as réussi cet exercice **Bien joué** tu peux passer à l'apprentissage des **Dictionnaires** parcontre si tu as pas réussi ou que tu es pas sur d'avoir compris hésites pas à recommencer l'apprentissage ou à m'envoyer un message privé pour que je t'explique !*",

        'dictionnaires' :   "**Correction Exercice : Dictionnaires**\n"
                            "*Pour cet exercice vous aviez besoin d'utiliser **max()** pour trouver la note la plus élevé et vous deviez aussi utiliser le input dans le dictionnaire pour écrire moins de ligne. Voici donc la correction : *\n"
                            "```Dictionnaire = {\n"
                            "    'Nom' : input('Nom'),\n"
                            "    'Prenom' : input('Prenom'),\n"
                            "    'Age' : int(input('Age')),\n"
                            "    'Département' : int(input('departement')),\n"
                            "    'Resultat_evaluation' : [0, 12, 9, 18, 16]\n"
                            "    }\n\n"
                            "liste = Dictionnaire['Resultat_evaluation']\n\n"
                            "print(Dictionnaire, max(liste))```"
                            "\n\n*Si tu as réussi cet exercice **Bien joué** tu peux passer à l'apprentissage des **Boucles** parcontre si tu as pas réussi ou que tu es pas sur d'avoir compris hésites pas à recommencer l'apprentissage ou à m'envoyer un message privé pour que je t'explique !*",

    'boucles' : "**Correction Exercice : Dictionnaires**\n"
                "*Pour cet exercice vous aviez besoin d'utiliser les 2 types de boucles en plus d'une condition pour comparer les éléments. Voici donc la correction : *\n"
                "```liste = ['Banana','Chocolate','Lemon','Pistachio','Raspberry','Strawberry','Vanilla']\n"
                "print(liste)\n"
                "dictionnaire = {1 : 'Banana',2 : 'Chocolate',3 : 'Lemon',4 : 'Pistachio',5 : 'Raspberry',6 : 'Strawberry',7 : 'Vanilla'}\n"
                "parfum = input('Quel parfum désirez vous ?')\n\n"
                "while parfum not in liste:\n"
                "    parfum = input('Quel parfum désirez vous ?')\n\n"
                "for numero,gout in dictionnaire.items():\n"
                "    if gout == parfum:\n"
                "        print('La position du parfum est',numero)```"
                "\n\n*Si tu as réussi cet exercice **Bien joué** tu peux passer à l'apprentissage des **Fonctions** parcontre si tu as pas réussi ou que tu es pas sur d'avoir compris hésites pas à recommencer l'apprentissage ou à m'envoyer un message privé pour que je t'explique !*",

    'fonctions':"**Correction Exercice : Dictionnaires**\n"
                "*Pour cet exercice vous aviez besoin d'utiliser une varaible pour faire un compteur, une boucle for et pour terminer savoir utiliser les dictionnaires + fonctions. Voici donc la correction : *\n"
                "```def from_roman_numeral(roman_numeral):\n"
                "    count = 0\n"
                "    dico = {\n"
                "        'V' : 5,\n"
                "        'I' : 1,\n"
                "        'L' : 50,\n"
                "        'X' : 10,\n"
                "        'D' : 500,\n"
                "        'C' : 100,\n"
                "        'M' : 1000\n"
                "        }\n"
                "    l = []\n"
                "    for e in roman_numeral:\n"
                "        l.append(dico[e])\n"
                "    for e in range(0,len(l)):\n"
                "        if e != len(l)-1:\n"
                "            if l[e] >= l[e+1]:\n"
                "                count += l[e]\n"
                "            else:\n"
                "                count -= l[e]\n"
                "        else:\n"
                "            count += l[e]\n"
                "    return count```"
                "Bien joué si tu as réussis cet exercice ça veut dire que tu maitrises les bases fondamental de python par-contre si tu n'as pas réussis je t'encourage à lire cette correction et de comprendre tes erreurs !",

    }
    return correction[num]
